# Generated by Django 3.2 on 2023-04-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sip', models.CharField(max_length=16)),
                ('method', models.CharField(max_length=10)),
                ('uri', models.TextField()),
                ('sport', models.IntegerField()),
                ('username', models.CharField(max_length=256)),
                ('cip', models.CharField(max_length=16)),
                ('useragent', models.TextField()),
                ('referer', models.TextField()),
                ('status', models.TextField()),
                ('substatus', models.TextField()),
                ('win32status', models.TextField()),
                ('timetaken', models.TextField()),
                ('country', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=128)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.entry')),
            ],
        ),
    ]
